/**
 * Standard interface for all Marketplace and Protocol Adapters in the A2A ecosystem.
 *
 * Every external marketplace (OKX Web3, Hansa, Mock, etc.) must implement
 * MarketplaceAdapter to interact with the autonomous core engine.
 */

import type { AgentCard } from './a2a/agent-card.js';

export interface TaskArtifact {
  /** Output generated by the agent (text, code, or structured JSON). */
  content: string | Record<string, unknown>;
  /** Model used for generation (e.g. gemini-1.5-flash, groq/llama-3.3-70b). */
  model: string;
  /** ISO-8601 timestamp of task completion. */
  completedAt: string;
  /** Optional metadata produced during execution. */
  metadata?: Record<string, unknown>;
}

export interface Task {
  /** Unique task identifier on the target marketplace. */
  id: string;
  /** Identifier of the marketplace (e.g. "okx", "hansa", "mock"). */
  marketplace: string;
  /** The natural language prompt or structured task payload to execute. */
  prompt: string;
  /** Financial compensation offered for successful completion. */
  reward: number;
  /** Settlement currency (e.g. "USD", "USDT", "USDC"). */
  currency: string;
  /** Maximum timestamp or deadline for submission. */
  deadline?: string;
  /** Marketplace-specific metadata. */
  metadata?: Record<string, unknown>;
}

export interface SubmissionReceipt {
  /** Whether the marketplace accepted the submitted artifact. */
  success: boolean;
  /** Task ID matching the submitted task. */
  taskId: string;
  /** On-chain transaction hash or platform settlement ID, if available. */
  settlementId?: string;
  /** Timestamp when submission was acknowledged. */
  submittedAt: string;
  /** Error message if rejected by the marketplace. */
  error?: string;
}

/**
 * Standard contract that all marketplace adapters must implement.
 */
export interface MarketplaceAdapter {
  /** Unique identifier for this adapter instance (e.g. "okx", "hansa"). */
  readonly id: string;

  /**
   * Polls the marketplace for currently available unassigned tasks.
   * @returns Array of tasks matching the agent's criteria.
   */
  pollTasks(): Promise<Task[]>;

  /**
   * Submits a completed task artifact along with an Ed25519 cryptographic signature.
   *
   * @param taskId Unique identifier of the task being fulfilled.
   * @param artifact The task result and execution metadata.
   * @param signature Cryptographic Ed25519 signature over canonical artifact content.
   * @returns Receipt indicating settlement or acceptance status.
   */
  submitArtifact(
    taskId: string,
    artifact: TaskArtifact,
    signature: string,
  ): Promise<SubmissionReceipt>;

  /**
   * Retrieves the standardized A2A Agent Card for discovery and verification.
   * @returns Canonical AgentCard JSON representation.
   */
  getAgentCard(): AgentCard;
}
